### ISSUE TITLE
Nixon/Lodge Broken :(

### ISSUE THREAD

**Issue by JFKERRY** [newcampaigntrail/newcampaigntrail.github.io#154]
![image](https://user-images.githubusercontent.com/111160869/218475203-1fb6980c-de03-4e0a-9bed-c862a0d9627e.png)

**Comment by JFKERRY** [comment]
oh yeah 
        		// ### 2024G ###
                // You WILL win Oregon - Win Oregon as Carson while losing!
                /*
                if (!run.achievements["youwillwinoregon"] && e.candidate_last_name == "Carlson" && e.election_id == 20 && campaignTrail_temp.difficulty_level_multiplier <= 0.97 && 23 == campaignTrail_temp.final_state_results[36].result[0].candidate==200 && e.final_outcome =="lose") {
                    unlockAchievement(among, "youwillwinoregon", "", "You <b>WILL</b> win Oregon")
                } else
                */
``
fun plz re ad this

**Comment by ItsAstronomical** [comment]
Nixon/Lodge from 1964N does not due to a combination of how the new mod loader works. There is 1 code one per mod - 1964N was coded with separate Code 1s for each Candidate (This is also why 1936c is broken). Supposedly, a push was made a few days ago which claimed to fix it, but alas, it appears it has not. As far as I know, after 1968n, the mod makers will go back and fix this - and going forward I will make it clear how the new mod loader works. 

As for the achievement, the dev team's consensus is not to re-add it.
